version: '2'

services:

  quexc:
    image: acspri/quexc
    ports:
      - 127.0.0.1:8087:80
    environment:
      QUEXC_DB_PASSWORD: example
      QUEXC_ADMIN_PASSWORD: password

  mysql:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
